version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/api-creator
hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      runas: ec2-user




